Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
output = pytesseract.image_to_string(im)
print(output)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pytesseract/pytesseract.py:255[0m, in [0;36mrun_tesseract[0;34m(input_filename, output_filename_base, extension, lang, config, nice, timeout)[0m
[1;32m    254[0m [38;5;28;01mtry[39;00m:
[0;32m--> 255[0m     proc [38;5;241m=[39m [43msubprocess[49m[38;5;241;43m.[39;49m[43mPopen[49m[43m([49m[43mcmd_args[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43msubprocess_args[49m[43m([49m[43m)[49m[43m)[49m
[1;32m    256[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m e:

File [0;32m/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/subprocess.py:971[0m, in [0;36mPopen.__init__[0;34m(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize)[0m
[1;32m    968[0m             [38;5;28mself[39m[38;5;241m.[39mstderr [38;5;241m=[39m io[38;5;241m.[39mTextIOWrapper([38;5;28mself[39m[38;5;241m.[39mstderr,
[1;32m    969[0m                     encoding[38;5;241m=[39mencoding, errors[38;5;241m=[39merrors)
[0;32m--> 971[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_execute_child[49m[43m([49m[43margs[49m[43m,[49m[43m [49m[43mexecutable[49m[43m,[49m[43m [49m[43mpreexec_fn[49m[43m,[49m[43m [49m[43mclose_fds[49m[43m,[49m
[1;32m    972[0m [43m                        [49m[43mpass_fds[49m[43m,[49m[43m [49m[43mcwd[49m[43m,[49m[43m [49m[43menv[49m[43m,[49m
[1;32m    973[0m [43m                        [49m[43mstartupinfo[49m[43m,[49m[43m [49m[43mcreationflags[49m[43m,[49m[43m [49m[43mshell[49m[43m,[49m
[1;32m    974[0m [43m                        [49m[43mp2cread[49m[43m,[49m[43m [49m[43mp2cwrite[49m[43m,[49m
[1;32m    975[0m [43m                        [49m[43mc2pread[49m[43m,[49m[43m [49m[43mc2pwrite[49m[43m,[49m
[1;32m    976[0m [43m                        [49m[43merrread[49m[43m,[49m[43m [49m[43merrwrite[49m[43m,[49m
[1;32m    977[0m [43m                        [49m[43mrestore_signals[49m[43m,[49m
[1;32m    978[0m [43m                        [49m[43mgid[49m[43m,[49m[43m [49m[43mgids[49m[43m,[49m[43m [49m[43muid[49m[43m,[49m[43m [49m[43mumask[49m[43m,[49m
[1;32m    979[0m [43m                        [49m[43mstart_new_session[49m[43m)[49m
[1;32m    980[0m [38;5;28;01mexcept[39;00m:
[1;32m    981[0m     [38;5;66;03m# Cleanup if the child failed starting.[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/subprocess.py:1863[0m, in [0;36mPopen._execute_child[0;34m(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)[0m
[1;32m   1862[0m         err_msg [38;5;241m=[39m os[38;5;241m.[39mstrerror(errno_num)
[0;32m-> 1863[0m     [38;5;28;01mraise[39;00m child_exception_type(errno_num, err_msg, err_filename)
[1;32m   1864[0m [38;5;28;01mraise[39;00m child_exception_type(err_msg)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'tesseract'

During handling of the above exception, another exception occurred:

[0;31mTesseractNotFoundError[0m                    Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m output [38;5;241m=[39m [43mpytesseract[49m[38;5;241;43m.[39;49m[43mimage_to_string[49m[43m([49m[43mim[49m[43m)[49m
[1;32m      2[0m [38;5;28mprint[39m(output)

File [0;32m/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pytesseract/pytesseract.py:423[0m, in [0;36mimage_to_string[0;34m(image, lang, config, nice, output_type, timeout)[0m
[1;32m    418[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    419[0m [38;5;124;03mReturns the result of a Tesseract OCR run on the provided image to string[39;00m
[1;32m    420[0m [38;5;124;03m"""[39;00m
[1;32m    421[0m args [38;5;241m=[39m [image, [38;5;124m'[39m[38;5;124mtxt[39m[38;5;124m'[39m, lang, config, nice, timeout]
[0;32m--> 423[0m [38;5;28;01mreturn[39;00m [43m{[49m
[1;32m    424[0m [43m    [49m[43mOutput[49m[38;5;241;43m.[39;49m[43mBYTES[49m[43m:[49m[43m [49m[38;5;28;43;01mlambda[39;49;00m[43m:[49m[43m [49m[43mrun_and_get_output[49m[43m([49m[38;5;241;43m*[39;49m[43m([49m[43margs[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[43m[[49m[38;5;28;43;01mTrue[39;49;00m[43m][49m[43m)[49m[43m)[49m[43m,[49m
[1;32m    425[0m [43m    [49m[43mOutput[49m[38;5;241;43m.[39;49m[43mDICT[49m[43m:[49m[43m [49m[38;5;28;43;01mlambda[39;49;00m[43m:[49m[43m [49m[43m{[49m[38;5;124;43m'[39;49m[38;5;124;43mtext[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[43mrun_and_get_output[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m[43m}[49m[43m,[49m
[1;32m    426[0m [43m    [49m[43mOutput[49m[38;5;241;43m.[39;49m[43mSTRING[49m[43m:[49m[43m [49m[38;5;28;43;01mlambda[39;49;00m[43m:[49m[43m [49m[43mrun_and_get_output[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m[43m,[49m
[1;32m    427[0m [43m[49m[43m}[49m[43m[[49m[43moutput_type[49m[43m][49m[43m([49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pytesseract/pytesseract.py:426[0m, in [0;36mimage_to_string.<locals>.<lambda>[0;34m()[0m
[1;32m    418[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    419[0m [38;5;124;03mReturns the result of a Tesseract OCR run on the provided image to string[39;00m
[1;32m    420[0m [38;5;124;03m"""[39;00m
[1;32m    421[0m args [38;5;241m=[39m [image, [38;5;124m'[39m[38;5;124mtxt[39m[38;5;124m'[39m, lang, config, nice, timeout]
[1;32m    423[0m [38;5;28;01mreturn[39;00m {
[1;32m    424[0m     Output[38;5;241m.[39mBYTES: [38;5;28;01mlambda[39;00m: run_and_get_output([38;5;241m*[39m(args [38;5;241m+[39m [[38;5;28;01mTrue[39;00m])),
[1;32m    425[0m     Output[38;5;241m.[39mDICT: [38;5;28;01mlambda[39;00m: {[38;5;124m'[39m[38;5;124mtext[39m[38;5;124m'[39m: run_and_get_output([38;5;241m*[39margs)},
[0;32m--> 426[0m     Output[38;5;241m.[39mSTRING: [38;5;28;01mlambda[39;00m: [43mrun_and_get_output[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m,
[1;32m    427[0m }[output_type]()

File [0;32m/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pytesseract/pytesseract.py:288[0m, in [0;36mrun_and_get_output[0;34m(image, extension, lang, config, nice, timeout, return_bytes)[0m
[1;32m    277[0m [38;5;28;01mwith[39;00m save(image) [38;5;28;01mas[39;00m (temp_name, input_filename):
[1;32m    278[0m     kwargs [38;5;241m=[39m {
[1;32m    279[0m         [38;5;124m'[39m[38;5;124minput_filename[39m[38;5;124m'[39m: input_filename,
[1;32m    280[0m         [38;5;124m'[39m[38;5;124moutput_filename_base[39m[38;5;124m'[39m: temp_name,
[0;32m   (...)[0m
[1;32m    285[0m         [38;5;124m'[39m[38;5;124mtimeout[39m[38;5;124m'[39m: timeout,
[1;32m    286[0m     }
[0;32m--> 288[0m     [43mrun_tesseract[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    289[0m     filename [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mkwargs[[38;5;124m'[39m[38;5;124moutput_filename_base[39m[38;5;124m'[39m][38;5;132;01m}[39;00m[38;5;132;01m{[39;00mextsep[38;5;132;01m}[39;00m[38;5;132;01m{[39;00mextension[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    290[0m     [38;5;28;01mwith[39;00m [38;5;28mopen[39m(filename, [38;5;124m'[39m[38;5;124mrb[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m output_file:

File [0;32m/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pytesseract/pytesseract.py:260[0m, in [0;36mrun_tesseract[0;34m(input_filename, output_filename_base, extension, lang, config, nice, timeout)[0m
[1;32m    258[0m         [38;5;28;01mraise[39;00m
[1;32m    259[0m     [38;5;28;01melse[39;00m:
[0;32m--> 260[0m         [38;5;28;01mraise[39;00m TesseractNotFoundError()
[1;32m    262[0m [38;5;28;01mwith[39;00m timeout_manager(proc, timeout) [38;5;28;01mas[39;00m error_string:
[1;32m    263[0m     [38;5;28;01mif[39;00m proc[38;5;241m.[39mreturncode:

[0;31mTesseractNotFoundError[0m: tesseract is not installed or it's not in your PATH. See README file for more information.

